idf_component_register(SRCS "main.c"
                            "wifi_failover.c"
                            "vapi_app.c"
                            "vapi_client.c"
                            "vapi_media.c"
                            "aec_probe.c"
                            "controls.c"
                            "board.c"
                            "display.c"
                       INCLUDE_DIRS ".")
